image:
  repository: ghcr.io/brandme-labs/brandme-gateway
  tag: latest
  pullPolicy: IfNotPresent

env:
  oauthClientId: ""
  oauthClientSecret: ""
  defaultRegion: "us-east1"
  natsUrl: "nats://nats:4222"
  port: 8080

service:
  type: ClusterIP
  port: 8080

resources: {}
